default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: blogstrap_development
  port: 5433
  host: localhost
  username: postgres
  password: 123456

test:
  <<: *default
  database: blogstrap_test

production:
  <<: *default
  database: blogstrap_production
  username: blogstrap
  password: <%= ENV["BLOGSTRAP_DATABASE_PASSWORD"] %>
